# https://docs.docker.com/compose/overview/
version: '3.7'

services:
  # http://elk-docker.readthedocs.io/
  elk:
    container_name: cdp_api_dev
    image: sebp/elk:622
    ports:
      - '5601:5601'
      - '9200:9200'
      - '5044:5044'
    volumes:
      - elk:/var/lib/elasticsearch

volumes:
  elk:
    name: cdp_api_elk
